slim-login: avoid calling external 'id' program

diff --git a/debian/custom/slim-login b/debian/custom/slim-login
--- a/debian/custom/slim-login
+++ b/debian/custom/slim-login
@@ -7,7 +7,7 @@ TEXTDOMAINDIR=/usr/share/locale
 TEXTDOMAIN=slim-login
 
 [[ $DISPLAY ]] || { echo "There is no xserver running. Exiting..." ; exit 1 ; }
-[[ $(id -u) -eq 0 ]] || { yad --image "error" --title "!" --button=OK --text "root (sudo) authorization required \! \n\nCannot continue." ; exit 1 ; }
+[ "$UID" !="0" ] || { yad --image "error" --title "!" --button=OK --text "root (sudo) authorization required \! \n\nCannot continue." ; exit 1 ; }
 [[ -e /usr/local/bin/yad ]] || { echo "yad (provided by 'antix-goodies' package) missing; cannot proceed"; exit 1; }
 
 if [ ! -w /etc/slim.conf ]; then
