Update slim-login

diff --git a/debian/custom/slim-login b/debian/custom/slim-login
--- a/debian/custom/slim-login
+++ b/debian/custom/slim-login
@@ -7,7 +7,9 @@ TEXTDOMAINDIR=/usr/share/locale
 TEXTDOMAIN=slim-login
 
 [[ $DISPLAY ]] || { echo "There is no xserver running. Exiting..." ; exit 1 ; }
-[ "$UID" !="0" ] || { yad --image "error" --title "!" --button=OK --text "root (sudo) authorization required \! \n\nCannot continue." ; exit 1 ; }
+if [ "$UID" !="0" ]; then
+    yad --image "error" --title "!" --button=OK --text "root (sudo) authorization required \! \n\nCannot continue." ; exit 1 ;
+fi
 [[ -e /usr/local/bin/yad ]] || { echo "yad (provided by 'antix-goodies' package) missing; cannot proceed"; exit 1; }
 
 if [ ! -w /etc/slim.conf ]; then
